### ISSUE TITLE
计算月出时刻问题

### ISSUE THREAD

**Issue by clfeng66** [Starainrt/astro#2]
感谢分享，在测试过程，发现输入当前时间，月出时刻返回：-4713-12-29 12:00:00 +0805 LMT ERROR:月亮已在（昨日/明日）（升起/降下）。

**Comment by Starainrt** [comment]
存在这样的场景：某地月亮在昨天23时59分升起，今日12时落下，下次升起时间为明日0时50分。
这样的话，今日月亮实际上是没有升起时间的，故会报这样的错。

**Comment by Starainrt** [comment]
不过因为时区的问题，非上述情景下的确会有时区转换失败导致出现这个错误，目前已经修复。

**Comment by clfeng66** [comment]
感谢，
刚做了更新，拿2021年3月4日和2021年3月5日举例，我发现月出时间都会报错，
我拿其他方数据对照今天的月出时间为23:33，这里是否还是存在问题？

**Comment by Starainrt** [comment]
能否提供下传入的经纬度和时区？我复现下。

**Comment by clfeng66** [comment]
就是在提供的范例测试，经纬度默认，只改了时间，
cst := time.FixedZone("CST", 8*3600)
date := time.Date(2021, 03, 4, 2, 40, 30, 8, cst)
fmt.Println(moon.RiseTime(date, 117, 40, true)) //东经117北纬40度月出时刻
输出：-4713-12-29 12:05:43 +0805 LMT ERROR:月亮已在（昨日/明日）（升起/降下）

**Comment by Starainrt** [comment]
感谢，算法中把一个减号写成了加号导致的，已经修复了。

cst := time.FixedZone("CST", 8*3600)
date := time.Date(2021, 3, 4, 8, 8, 8, 8, cst)                     //指定2021年3月4日8时8分8秒
fmt.Println(moon.RiseTime(date.Add(time.Hour*-24), 117, 40, true)) //东经117北纬40度月出时刻
fmt.Println(moon.RiseTime(date, 117, 40, true))                    //东经117北纬40度月出时刻
fmt.Println(moon.RiseTime(date.Add(time.Hour*24), 117, 40, true))  //东经117北纬40度月出时刻
fmt.Println(moon.RiseTime(date.Add(time.Hour*48), 117, 40, true))  //东经117北纬40度月出时刻

分别计算3号、4号、5号、6号的月出数据：

2021-03-03 22:46:21.281340122 +0800 CST <nil>
-4713-12-29 12:00:00 +0800 CST ERROR:月亮已在（昨日/明日）（升起/降下）
2021-03-05 00:00:13.28305006 +0800 CST <nil>
2021-03-06 01:13:01.357567012 +0800 CST <nil>

与其他天文软件的结果比对了，这次是ok的。今天（4号）月亮是在5号的零点升起。
