### ISSUE TITLE
VB,php版本的代码能分享吗？

### ISSUE THREAD

**Issue by fc13240** [Starainrt/astro#4]
VB,php版本的代码能分享吗？

**Comment by Starainrt** [comment]
php 见旧版本：https://github.com/Starainrt/Astro-older
VB是10年前的版本了，后续没更新，就不提供了。

**Comment by Aquarian-Age** [comment]
搭车问一下每个月的朔　望怎么算呢?

**Comment by Starainrt** [comment]
> 搭车问一下每个月的朔　望怎么算呢?

旧的接口需要传入一个float64类型的”年份日期“，比如2021年7月1号，则需要传入2021.5，其中的.5代表已过去了半年，的确不方便。

新增了基于time.Time的接口，更方便点，示例见 ： [https://github.com/Starainrt/astro/blob/c0bcbbb42a60864df25fc4c5d653f472685f1c8f/moon/moon_test.go](https://github.com/Starainrt/astro/blob/c0bcbbb42a60864df25fc4c5d653f472685f1c8f/moon/moon_test.go)
