### ISSUE TITLE
为什么我这里计算出来的民用朦影不够准确

### ISSUE THREAD

**Issue by Evereen2023** [Starainrt/astro#8]

**Comment by Evereen2023** [comment]
// 解析输入的时间
	t, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		context.JSON(http.StatusBadRequest, gin.H{"error": "invalid time format, should be YYYY-MM-DD"})
		return
	}

**Comment by Evereen2023** [comment]
// 自定义计算民用昏朦的函数
func CalculateCivilTwilight(t time.Time, long float64, lat float64) (time.Time, time.Time, error) {
	// 计算日出和日落时间（可以使用已有的sun.RiseTime和sun.DownTime）
	sunrise, err := sun.RiseTime(t, long, lat, 0, true)
	if err != nil {
		return time.Time{}, time.Time{}, err
	}
	sunset, err := sun.DownTime(t, long, lat, 0, true)
	if err != nil {
		return time.Time{}, time.Time{}, err
	}

	// 计算民用昏暗的开始和结束时间，假设太阳高度角为-6度
	morningTwilight := sunrise.Add(-time.Minute * 30) // 假设30分钟为民用昏暗开始时间
	eveningTwilight := sunset.Add(time.Minute * 30)   // 假设30分钟为民用昏暗结束时间

	return morningTwilight, eveningTwilight, nil
}

**Comment by Evereen2023** [comment]
ai解决方法如下：
// 自定义计算民用昏朦的函数
func CalculateCivilTwilight(t time.Time, long float64, lat float64) (time.Time, time.Time, error) {
	// 计算日出和日落时间（可以使用已有的sun.RiseTime和sun.DownTime）
	sunrise, err := sun.RiseTime(t, long, lat, 0, true)
	if err != nil {
		return time.Time{}, time.Time{}, err
	}
	sunset, err := sun.DownTime(t, long, lat, 0, true)
	if err != nil {
		return time.Time{}, time.Time{}, err
	}

	// 计算民用昏暗的开始和结束时间，假设太阳高度角为-6度
	morningTwilight := sunrise.Add(-time.Minute * 30) // 假设30分钟为民用昏暗开始时间
	eveningTwilight := sunset.Add(time.Minute * 30)   // 假设30分钟为民用昏暗结束时间

	return morningTwilight, eveningTwilight, nil
}

**Comment by Starainrt** [comment]
时区转换存在bug，目前您可以在解析时间时手动设置时区暂时规避这个问题，这个bug会尽快修复：
```
       // 解析输入的时间
       loc, err := time.LoadLocation("Asia/Shanghai")
	if err != nil {
		//do something
	}
	now, t := time.ParseInLocation("2006-01-02", dateStr, loc)
        if err != nil {
	    context.JSON(http.StatusBadRequest, gin.H{"error": "invalid time format, should be YYYY-MM-DD"})
	    return
        }
```

**Comment by Starainrt** [comment]
>{ "eveningTwilight": "2024-10-22T09:13:00+08:00", "morningTwilight": "2024-10-21T21:32:35+08:00", "sunrise": "2024-10-22T06:01:57+08:00", "sunset": "2024-10-22T16:43:40+08:00" }
>最后返回的是这个，而气象局当天给出的是
>05:33 至 06:02 | 29 分钟

time.Parse() 将字符串转换为`time.Time`对象，对象中默认时区是UTC时间，也就是北京时间-8小时。
`sun.MorningTwilight()` 计算出朦影时间后，忽视了`time.Time`对象时区强行转为当地时间，导致了bug。

`morningTwilight": "2024-10-21T21:32:35+08:00` 再加8小时就是 `"2024-10-22T05:32:35+08:00`，与气象局的05:33一致。

**Comment by Evereen2023** [comment]
现在不设置时区会全部少八个小时
比如
传参：latitude=43.8860&longitude=125.3245&date=2024-11-01
返回：
{
"eveningTwilight": "2024-11-01T08:59:00Z",
"morningTwilight": "2024-10-31T21:44:55Z",
"sunrise": "2024-10-31T22:14:55Z",
"sunset": "2024-11-01T08:29:01Z"
}

**Comment by Evereen2023** [comment]
经过测试，还需要手动指定时区才能正常运行

**Comment by Starainrt** [comment]
> 现在不设置时区会全部少八个小时 比如 传参：latitude=43.8860&longitude=125.3245&date=2024-11-01 返回： { "eveningTwilight": "2024-11-01T08:59:00Z", "morningTwilight": "2024-10-31T21:44:55Z", "sunrise": "2024-10-31T22:14:55Z", "sunset": "2024-11-01T08:29:01Z" }

这个是符合预期的，因为时间传进来是什么时区，返回的时间也是那个时区，date=2024-11-01，默认UTC时间，返回就是UTC，需要手动修正时区到当地时间。

不自动转换到当地时区的原因在于，给定经纬度与当地时区的映射关系涉及到不同国家法律，比如中国从新疆到黑龙江横跨五个自然时区，但全国统一用北京时间。同时，在此之上可能还涉及到夏令时、冬令时等调整，而这个package主要还是关注于纯粹的天文算法上。

如果您业务主要聚焦于国内，可以Parse日期时强制设置东八区，否则，可以结合其他时区转换package来达到自动转换到当地时区的效果，如：https://github.com/evanoberholster/timezoneLookup

**Comment by Starainrt** [comment]
或者，传参增加timezone一项，读取客户端时区设置，传到服务端，服务端用传上来的时区做调用。
传参：latitude=43.8860&longitude=125.3245&date=2024-11-01&timezone=8
```
tz :=time.FixedZone("CTS", timezone*3600)
date,_ :=time.ParseInLocation("2006-01-02", dateStr, tz)
```

**Comment by Evereen2023** [comment]
谢谢谢谢，太谢谢了，这个库很好！
